## Data gathering
data_gathering:
  path: "C:/Users/gustavo/Documents/Data Science/08-GitHub/Portifolio/Regression/house_prices_single_model/data/raw"
  train: "train.csv"
  test: "test.csv"
  competition: "house-prices-advanced-regression-techniques"

processed_data:
  path: 'C:/Users/gustavo/Documents/Data Science/08-GitHub/Portifolio/Regression/house_prices_single_model/data/processed'
  train: "train.parquet"
  test: "test.parquet"

## feat engineering
pipe_feat_eng:
  path: 'C:/Users/gustavo/Documents/Data Science/08-GitHub/Portifolio/Regression/house_prices_single_model/models'

## Feature selection
feat_selection:
  path: 'C:/Users/gustavo/Documents/Data Science/08-GitHub/Portifolio/Regression/house_prices_single_model/data/processed'
  input: "train.parquet"
  X_train: "feat_X_train.parquet"
  X_val: "feat_X_val.parquet"
  y_train: "feat_y_train.parquet"
  y_val: "feat_y_val.parquet"

feat_selection_params:
  pipe_version: 1
  random_state: 23
  pca_threshold: 0.95
  val_size: 0.25
  cols_2_drop:
    - Id
    - Alley 
    - Fence 
    - MiscFeature
    - PoolQC
    - MasVnrType
    - BsmtHalfBath
    - 3SsnPorch
    - ScreenPorch
    - PoolArea
    - MiscVal
    - Street 
    - Utilities
    - Condition2
    - RoofStyle
    - LowQualFinSF
    - KitchenAbvGr
    - BsmtFinType1
    - BsmtFinType2
    - Exterior1st
    - Exterior2nd
    - Condition1
    - Functional
    - ExterCond
    - HeatingQC
    - MSSubClass
    - MoSold
    - EnclosedPorch
    - BsmtFinSF2
    - YrSold   
    - OverallCond
    - BsmtFullBath
    - HouseStyle 
    - PavedDrive
    - GarageCars
    - TotRmsAbvGrd
    - GarageYrBlt
    - FireplaceQu
    - LandContour 
    - RoofMatl
    - BldgType 
    - LandSlope
    - Electrical
    - LotShape 
    - Fireplaces 
    - BsmtUnfSF
    - LotFrontage
    - Neighborhood 
    - LotConfig
  cat_var:
    - MSZoning                
    - ExterQual    
    - Foundation
    - BsmtQual
    - BsmtCond
    - BsmtExposure
    - Heating    
    - CentralAir    
    - KitchenQual        
    - GarageType
    - GarageFinish
    - GarageQual    
    - SaleType
    - SaleCondition
    - GarageCond            
  num_var_1:     
    - OverallQual
    - YearBuilt
    - YearRemodAdd    
    - GrLivArea    
    - FullBath
    - HalfBath
    - BedroomAbvGr               
    - GarageArea    
  num_var_2:    
    - LotArea
    - MasVnrArea
    - BsmtFinSF1    
    - TotalBsmtSF
    - 1stFlrSF
    - 2ndFlrSF
    - WoodDeckSF
    - OpenPorchSF
  target: 
    - SalePrice

## Model selection
model_selection:  
  cols_2_drop:

  score: 'neg_root_mean_squared_error'
model:
  path: 'C:/Users/gustavo/Documents/Data Science/08-GitHub/Portifolio/Regression/house_prices_single_model/models'
  model_version: 1

## Model
train_model: 
  path: 'C:/Users/gustavo/Documents/Data Science/08-GitHub/Portifolio/Regression/house_prices_single_model/data/processed'
  model_params: 'C:/Users/gustavo/Documents/Data Science/08-GitHub/Portifolio/Regression/house_prices_single_model/data/reports'


## Save reports
save_reports:
  path_reports: 'C:/Users/gustavo/Documents/Data Science/08-GitHub/Portifolio/Regression/house_prices_single_model/data/reports'
  path_plot: 'C:/Users/gustavo/Documents/Data Science/08-GitHub/Portifolio/Regression/house_prices_single_model/plots'

## Prediction
output_predict:
  path: 'C:/Users/gustavo/Documents/Data Science/08-GitHub/Portifolio/Regression/house_prices_single_model/data/processed'

## Submission
submission:
  path: 'C:/Users/gustavo/Documents/Data Science/08-GitHub/Portifolio/Regression/house_prices_single_model/data/submission'