init_path : "C:/Users/gustavo/Documents/Data Science/08-GitHub/Portifolio"

## Data gathering
data_gathering:  
  path: "Classification/dsa/raw"
  train: "dataset_treino.csv"
  test: "dataset_teste.csv"
  competition: "competicao-dsa-machine-learning-jan-2019"

processed_data:
  path: 'Classification/dsa/dsa_single_model/data/processed'
  train: "train.parquet"
  test: "test.parquet"

## feat engineering
pipe_feat_eng:
  path: 'Classification/dsa/dsa_single_model/models'

## Feature selection
feat_selection:
  path: 'Classification/dsa/dsa_single_model/data/processed'
  input: "train.parquet"
  X_train: "feat_X_train.parquet"
  X_val: "feat_X_val.parquet"
  y_train: "feat_y_train.parquet"
  y_val: "feat_y_val.parquet"

feat_selection_params:
  pipe_version: 1
  random_state: 23
  pca_threshold: 0.95
  val_size: 0.20
  cols_2_drop:
    - id     
  cat_var:    
  num_var:
    - num_gestacoes
    - glicose
    - pressao_sanguinea
    - grossura_pele
    - bmi
    - indice_historico
    - idade
    - insulina
  num_var_1:
    - insulina
    - pressao_sanguinea
    - glicose    
    - bmi
  num_var_2:
    - num_gestacoes
    - grossura_pele    
    - indice_historico
    - idade
  target: 
    - classe

## Model selection
model_selection:  
  cols_2_drop:
    - numerical_pipe__indice_historico
  score: 'accuracy'
model:
  path: 'Classification/dsa/dsa_single_model/models'
  model_version: 1

## Model
train_model: 
  path: 'Classification/dsa/dsa_single_model/data/processed'
  model_params: 'Classification/dsa/dsa_single_model/data/reports'


## Save reports
save_reports:
  path_reports: 'Classification/dsa/dsa_single_model/data/reports'
  path_plot: 'Classification/dsa/dsa_single_model/plots'

## Prediction
output_predict:
  path: 'Classification/dsa/dsa_single_model/data/processed'

## Submission
submission:
  path: 'Classification/dsa/dsa_single_model/data/submission'